research_task:
  description: >
    Conduct a thorough research on the latest developments in {topic}. Ensure the sources are reliable and publish recent, relevant information directly related to {topic}. 

    Compile a list of the most significant findings you discovered.

    Follow these rules:
    - Only include findings that are directly relevant to {topic}.
    - Do not include sources that are not directly related to the research topic. Avoid lists of articles or front pages of websites.
    - Summarize each finding in a few sentences, including all relevant information concisely.
    - Include the complete URL of the source where you found the information.
    - Include a minimum of 7 and a maximum of 10 findings in the list.
    - When using the Search Tool, your search query should be concise (e.g., "latest developments in {topic}").

    IMPORTANT INSTRUCTIONS ABOUT USING TOOLS: When using tools, DO NOT ESCAPE the underscore character "_", EVER. If you need to use a tool and pass in a parameter called 'search_query', you should write 'search_query', not 'search\_query'. THIS IS VERY IMPORTANT, else the tool will not work.

  expected_output: >
    A markdown document with the most significant findings. Each finding should contain the following:
    - Title of the finding
    - Summary of the finding
    - URL of the source where the finding was found

    Here is an example of the format of a finding that you could include in the document:

    <EXAMPLE>
      Finding 1:
      - Title: **Breakthrough in AI-Powered Healthcare**
      - **Summary:** Researchers have developed a new AI algorithm that significantly improves the accuracy of diagnosing certain medical conditions.
      - **URL:** [Source Article](https://www.example.com/ai-healthcare-breakthrough)
    </EXAMPLE>

edit_task:
  description: >
    Given the list of research findings, perform the following tasks:

    - Rewrite the title of each finding to make it more engaging and informative.
    - Add a paragraph to each finding that explains why it is important and how it can impact the readers.
    - Reorder the findings so that the most significant ones are at the top of the list based on their relevance and impact.
    - Verify that the findings are directly related to {topic} and are not off-topic. Remove any off-topic findings from the list.
    - Verify that the URLs are correct and lead to the appropriate source. They should lead to the relevant information, not a list of articles or a website's front page. If a URL is incorrect, request the researcher to provide the correct URL.
    - Do not search for additional findings or change the content of the findings. Only edit the existing findings.

    IMPORTANT INSTRUCTIONS ABOUT USING TOOLS: When using tools, DO NOT ESCAPE the underscore character "_", EVER. If you need to use a tool and pass in a parameter called 'search_query', you should write 'search_query', not 'search\_query'. THIS IS VERY IMPORTANT, else the tool will not work.

  expected_output: >
    A markdown document with all the research findings to be included in the report. The document should have a title related to the curated findings and a list of the findings.

    Each finding should contain:
    - Title:
    - Summary:
    - Why this is important:
    - Source: [URL of the source]

    Here is an example of a document that you are expected to produce:
    <EXAMPLE>
    Title of the Report: Advances in AI Technology

      - **Title:** Breakthrough in AI-Powered Healthcare
        **Summary:** Researchers have developed a new AI algorithm that significantly improves the accuracy of diagnosing certain medical conditions.
        **Why this is important:** This breakthrough is crucial because it has the potential to revolutionize healthcare by providing faster and more accurate diagnoses, ultimately saving lives and reducing costs.
        **Source:** [Source Article](https://www.example.com/ai-healthcare-breakthrough)

        [... more findings ...]
    </EXAMPLE>

newsletter_task:
  description: >
    Fill the following HTML template with exactly the same information that is given to you. Also, include the following text description for research topic at the beginning of the report in the space provided: {personal_message}

    (If there is no text_description , leave the space empty.)

    Follow these rules:
    - Do not truncate the information or change the order of the elements.
    - Do not modify the content of the research findings.
    - Do not add any additional information to the report.
    - Add ALL the research findings provided. Even if the template only shows one finding, you should include all the findings provided using the format in the template.

    {html_template}
  expected_output: >
    Return ONLY the contents of the HTML template, without any tripple quotes like '```', '```html' or any other text. 
    This output will be saved as a HTML file and sent to the subscribers.
